const country = 'Bulgaria';
let population = 7000000;
let halfPopulation = population / 2;
console.log(halfPopulation);
let increasedPopulation = population + 1;
console.log(increasedPopulation);
let finlandPopulation = 6000000;
console.log(population > finlandPopulation);
let averageWorldCountryPopulation = 33000000;
console.log(population > averageWorldCountryPopulation);
let description = country + ' is a country in Europe and its ' + population + ' people speak bulgarian';
console.log(description);